---
- name: Take care of Linux Mint 22 Workstation
  gather_facts: true
  connection: local
  hosts: all

  tasks:
  - name: Software
    ansible.builtin.include_role:
      name: software
    tags: always

  - name: System tweaks
    ansible.builtin.include_role:
      name: tweaks_system
    tags: always

