---
- name: User tweaks
  ansible.builtin.include_tasks: user.yml
  tags: always

- name: Cinnamon configuration
  ansible.builtin.include_tasks: cinnamon.yml
  tags: always

- name: System tweaks
  ansible.builtin.include_tasks: system.yml
  tags: always

- name: Text Editor
  ansible.builtin.include_tasks: xed.yml
  tags: always